set(EXTENSIONS_DIR ${CMAKE_CURRENT_LIST_DIR}/superbuild-extensions)
include(${CMAKE_CURRENT_LIST_DIR}/plugins/mc_kinova_sim_superbuild.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/interfaces/mc_kortex.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/plugins/mc_residual_estimation.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/plugins/minimum_jerk_task.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/plugins/mc_joystick_plugin.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/controllers/monodzukuri2024_kinova_demo.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/plugins/mc_ros_posture_pub_sub.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/controllers/posture_datastore_controller.cmake)
